FROM resin/rpi-raspbian:latest
MAINTAINER John Zhang <cdzhangw@gmail.com>

## Core Utilities
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y automake \
                       ca-certificates
