// Generated by CoffeeScript 1.8.0
(function() {
  exports.FixtureLoader = (function() {
    FixtureLoader.prototype.path = ['.'];

    function FixtureLoader() {
      if (process.argv.length < 4) {
        return;
      }
      this.path = this.path.concat(process.argv[2].split(';'));
    }

    FixtureLoader.prototype.require = function(module) {
      var currdir, e, path, _i, _len, _ref;
      currdir = process.cwd();
      _ref = this.path;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        path = _ref[_i];
        try {
          return require(path + '/' + module);
        } catch (_error) {
          e = _error;
        }
        try {
          return require(currdir + '/' + path + '/' + module);
        } catch (_error) {
          e = _error;
        }
      }
      throw 'Cannot find ' + module + ' because of '+e+e.stack;
    };

    return FixtureLoader;

  })();

}).call(this);
